:showtitle:
:doctype: article
:i: pass:[<a href="https://github.com/riku-ri/preview.adoc.nvim"><b>preview.adoc.nvim</b></a>]
:rkrpreview: https://github.com/riku-ri/preview.nvim[riku-ri/preview.nvim]

= {i}

This is a previewer for asciidoc format.

I moved from markdown to asciidoc currently,
it is mainly because:

- markdown has no variable
- markdown use tail space to break line

{i} is based on {rkrpreview}.
{rkrpreview} is a preview template for neovim.
{rkrpreview} contain some non-documentation file type,
like graphviz dot, R.

These file type may make a huge different between the source code and the products.
So auto scroll should not apply to them.

But I'm going to add the auto scroll feature for asciidoc.

== Requirements

=== For building

* golang

=== For using

* Linux
* neovim
+
____
vim may work, but I never test vim
____
* python3
* A web browser
+
____
link:preview.nvim[`preview.nvim`] use curl by default,
this can be set by vim variable `g:preview_browser`

> In fact `curl` do nothing as a browser.
> > This is to disable open a Linux browser in WSL.
> > > This is to disable open a Linux browser in WSL.
____
* asciidoctor
+
____
This is defined in
link:asciidoc.body.vim[asciidoc.body.vim] and
link:asciidoc.scroll.vim[asciidoc.scroll.vim],
replace `s:cmd` to change it
____

== Building

There is only a golang file `websocket.go`.
So after clone {i},
just go into the {i} root path and build a go project.
[,sh]
----
go mod init websocket
go mod tidy
go build
----

== Using

In neovim, source the link:preview.nvim[`preview.nvim`] in {i} root path.
For example,
[,sh]
----
git clone https://github.com/riku-ri/preview.adoc.nvim /tmp/apnv
cd /tmp/apnv
go mod init websocket
go mod tidy
go mod build
----
____
In the commands above,
it is recommended don't change `websocket` in
`git mod init websocket`.
Because the `preview.nvim` will startup a program named websocket,
if this changed, `go` may change the output binary file name too.
It may lead to `preview.nvim` connot find the file
____

After executing the command above, {i} should be in `/tmp/apnv`.
Run `:so /tmp/apnv/preview.nvim` may open a web browser and update from neovim content:

* If the `g:preview_browser` is not set,
the default "browser" `curl` will not show anything.
In such a case:
. Open another web browser
. Open file in the web browser
.. Go into the path where you are editing asciidoc file and open the html file.
	The html file should be with a strange number prefix, it is the neovim pid.
+
____
There is a subtle difference between "where you are editing asciidoc file"
and "where the asciidoc file exists" here.

For example, for a asciidoc file `/tmp/tmp/whatever.adoc`.
If you are in `/tmp` and then `nvim tmp/whatever.adoc`,
in the web browser you should go to `/tmp` path to find the html file.
____
