:gr: https://github.com/riku-ri/asciidoc-preview.nvim[asciidoc-preview.nvim]
:preview_nvim: https://github.com/riku-ri/preview.nvim[riku-ri/preview.nvim]

== {gr}

This is a previewer for asciidoc format.

I moved from markdown to asciidoc currently,
it is mainly because:

- markdown has no variable
- markdown use tail space to break line

{gr} is based on {preview_nvim}.
{preview_nvim} is a preview template for neovim.
{preview_nvim} contain some non-documentation file type,
like graphviz dot, R.

These file type may make a huge different between the source code and the products.
So auto scroll should not apply to them.

But I'm going to add the auto scroll feature for asciidoc.

=== Requirements

==== For building

- golang

==== For using

- Linux
- neovim
____
vim may work, but I never test vim
____
- python3
- A web browser
____
link:preview.nvim[`preview.nvim`] use chromium by default,
this can be set by vim variable `g:preview_browser`
____

=== Building

There is only a golang file `websocket.go`.
So after clone {gr},
just go into the {gr} root path and build a go project.
[,sh]
----
go mod init websocket
go mod tidy
go build
----

=== Using

In neovim, source the link:preview.nvim[`preview.nvim`] in {gr} root path.
For example,
[,sh]
----
git clone https://github.com/riku-ri/asciidoc-preview.nvim /tmp/apnv
cd /tmp/apnv
go mod init apnv
go mod tidy
go mod build
----
After executing the command above, {gr} should be in `/tmp/apnv`.
Run `:so /tmp/apnv/preview.nvim` may open a web browser and update from neovim content.
